- name: Install Docker on Amazon Linux 2
  hosts: all
  become_method: sudo
  becom_user: root
  tasks:
    - name: update yum package
      yum:
        update_cache: yes

    - name: Install required dependecies
      yum:
        name:
          - docker
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
