- name: Install Docker on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: update yum package
      dnf:
        update_cache: yes

    - name: Install required dependecies
      dnf:
        name:
          - docker
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
